### ISSUE TITLE
Links in footer are hard to see

### ISSUE THREAD

**Issue by wshirey** [dotnetfringe/dotnetfringe.github.io#148]
Could you try a different color combination for the links in the footer? Not color blind here, but sure it's hard for those who are to see the link.
![screen shot 2017-02-24 at 8 30 55 am](https://cloud.githubusercontent.com/assets/1452263/23307151/1a8f6baa-fa6c-11e6-8d55-1098341f7441.png)

**Comment by thoward** [comment]
Thanks for pointing that out! Fixed this a few commits back.
