### ISSUE TITLE
Updating for Geek Train & Bike Ride...

### ISSUE THREAD

**Issue by Adron** [dotnetfringe/dotnetfringe.github.io#150]
Getting the site updated for geek train and bike ride... 

This does beg the question though, are we just going with the theme that exists @thoward or is there another in the cooker that is ready to go live? Maybe I'll just add wording/content for the geek train and bike ride here and it can go live/update when the site is appropriately setup/ready for the update?

**Comment by thoward** [comment]
Ping. It's past deadline for this.
