### ISSUE TITLE
Update With Speakers

### ISSUE THREAD

**Issue by Adron** [dotnetfringe/dotnetfringe.github.io#151]
Hey @glennblock @thoward @saraford I know myself and @lenadroid don't really have any bandwidth until after OSCON to get the site updated with speakers, can any of you tackle getting it live on the site? Either way, putting this issue as a marker for speaker updates. Cheers!

**Comment by thoward** [comment]
I can create the template, but someone else will need to fill in the content. I'm planning to ship a version of the site with a few of the early-confirmed speakers. From that, I hope someone can fill in the rest by copying/pasting the markup and changing the information. It's not that hard, but it requires some time to sit down and fill in all the details. This will also need to be done on Lanyrd.

**Comment by glennblock** [comment]
I can definitely help here. I write a lot of content these days.

**Comment by thoward** [comment]
Ping. It's past deadline for this.
