### ISSUE TITLE
.NET Fringe Cycle Explorations of Portland

### ISSUE THREAD

**Issue by Adron** [dotnetfringe/dotnetfringe.github.io#60]
Is there anything in particular you'd like to see on a bike about (tour) of Portland before the conference? Last year we stopped by Ristretto Roasters (for a local roasted coffee), Velo Cult (Bicycle Culture) for a local micro-brew, and rolled back through town checking out various places.

Here's one loop idea. By no means a final, so add to it below in the thread!
![image](https://cloud.githubusercontent.com/assets/16567224/13893914/c6370234-ed1f-11e5-9acf-6d9579c7ed3d.png)

Which would include the following:
Things we'll see/do.
- **We'll pass the Steel Bridge** - 104 year old bridge that carries light rail, buses, pedestrians, bicycles, freight rail, passenger trains, and tractor trailors too. It's the work horse of Portland since 1912!
- **Cup & Bar** - one of the newest roasters in town, delivers by cargo bike, with open area to hang out/hack/bike to etc. Located by two of the new wonky crazy new residential towers going up.
- **Ladd's Addition**, one of the first neighborhoods, a planned streetcar neighborhood, of Portland platted and constructed between 1905 and 1930.
- **Apex Bar/Brewery**. Awesome bar with rocking tunes, more bike parking then you can imagine (and we'll still probably lock to trees) and an extremely impressive beer selection of local brews (dozens and dozens of them!).
- **Tilikum Bridge** is Portland's new transit, cycling, and pedestrian bridge. We'll route along some of the new MUP (Mixed Use Path) down to the bridge, where you'll get to see the confluence of streetcars, light rail, and buses funneling across the bridge and likely cyclists and pedestrians everywhere. It's a nifty bridge, just opened last year in September!
- We'll return along the southern end of the waterfront MUP (Mixed Use Path).

**Comment by Adron** [comment]
@AmadeusW any places or things you'd like to see? I'm sure you and Bianca have more than a few ideas about where and what to see/taste/drink/hillbomb in PDX.   :+1:   Pinging you both on Twitter too.

@rauhryan heya! Do you know the github/twitter accounts of the others who were on last year's ride? I'd love to get all of us rounded up plus @AmadeusW and crew to see where and what all we'd like to ride to and see. I've got a host of ideas that I'll post shortly, but want to get all the input on ideas before throwing mine out.  :8ball:

**Comment by rauhryan** [comment]
I'd be down for the same route, I loved easy st or easy way or whatever it was. 

It was a nice casual ride not too hard, even for someone who doesn't ride much and didn't have a great bike. 

I don't remember the names of any other riders, I know a few of them worked for Amazon and came down from Seattle.

**Comment by AmadeusW** [comment]
Looks good! The east side is way better to bike on than the downtown part, even though downtown has a bunch of cool stuff to see. We can always hit downtown up on foot.

I liked the neighborhood around NE Alberta St. I remember one road going north towards Alberta St that was particularly cool, but I forgot its name.
Another place I liked was the neighborhood between Burnside and Glisan around the block of 28th.
@BiancaPopescu what do you suggest?

**Comment by adron-orange** [comment]
Just to add some info and thoughts. I was focusing on having the route not cross any heavy auto traffic paths or we just stay on MUPs (bikes & pedestrians only). Of course, I'm open to any route across whatever to see anything - just want to make sure it's an attractive option for anybody that would want to check out the city the ole' ***good Portland way***.  :)

**Comment by Adron** [comment]
Just to add some info and thoughts. I was focusing on having the route not cross any heavy auto traffic paths or we just stay on MUPs (bikes & pedestrians only). Of course, I'm open to any route across whatever to see anything - just want to make sure it's an attractive option for anybody that would want to check out the city the ole' **_good Portland way**_.  :)

**Comment by adron-orange** [comment]
Feel free to add any thoughts... I'm going to start working up the final and will commit it to the main .NET Fringe [site](http://dotnetfringe.org/) and will post a comment with the exact anchor link when it's posted.

**Comment by Adron** [comment]
Feel free to add any thoughts... I'm going to start working up the final and will commit it to the main .NET Fringe [site](http://dotnetfringe.org/) and will post a comment with the exact anchor link when it's posted.
