### ISSUE TITLE
Are there recommended, or negotiated, hotels near the venue?

### ISSUE THREAD

**Issue by hyrmn** [dotnetfringe/dotnetfringe.github.io#75]
My wife and I both just bought tickets! We have our airline squared away and are shopping for hotels. I'm guessing it's more fun to stay where everyone else is staying so you can get in more after-hours mingle time.

Is there a recommended hotel? Bonus question, do you have any conference-negotiated rates? Otherwise, we'll keep looking through hotel and AirBnB options nearby.

**Comment by Adron** [comment]
Here's the basic area that is ideal to stay inside of
![image](https://cloud.githubusercontent.com/assets/278870/13940691/0e058b42-ef9d-11e5-91cd-17a52c9700e3.png)
Anything within this circle (which is about 90% of all hotels in the city) you'll be within a ~2-10 minute walk / transit / lyft / bike trip to the venue and within about a ~2-10 of any parties, the train station, the MAX to the airport, and basically every single thing that you'll need to get to. There will be more information on a room block in the coming 2-3 weeks as we finalize some negotiations with the area hotels. As always, once we have updated information about the hotels, it'll get posted here, the [.NET Fringe site](http://dotnetfringe.org/) and on the [.NET Fringe Lanyrd site](http://lanyrd.com/2016/netfringe/).

**Comment by Adron** [comment]
Also wanted to add, two great hotels that are one block and four blocks away respectively - and also super rad/hip/cool/fun/choice/premo etc, are the [Ace Hotel Portland](http://www.acehotel.com/portland) and the [Crystal Hotel](http://www.mcmenamins.com/CrystalHotel)

**Comment by Adron** [comment]
btw - hotels & such are updated onsite at http://dotnetfringe.org/#map

**Comment by adron-orange** [comment]
Airbnb is often the best. The hotels are all at summer prices at the moment, so a bit expensive.
